#Following the example script of timm library
Experiment:
  exp_id:             deit_small_8-8-4-0.01_rem          #Experiment Name
  path:               ./checkpoint #Path to save Experiment File, will store in "path/exp_id"
  checkpoint_hist:    10            #Number of checkpoints to keep
  dist:               True         #Start with dist launcher
  seed:               42
  debug:              False        #Enable debug output
  gpu_ids:            [0, 1, 2,3]            #GPUs to use

Model:
  model_name:       deit_small_patch16_224
  pretrained:       True

Trainer:
  name:             ImageClassification
  amp:              True          #Enable Automatic Mixed Precision
  batch_size:       256
  val_batch_size:   128
  epochs:           50
  prefetcher:       True
  eval_metric:      top1
  opt:    #Optimizer Settings
    name:           adamw
    params:
      lr:           5.0e-4        #Initial Learning Rate
      momentum:     0.9
      weight_decay: 2.0e-5
  sched:  #LR Scheduler Settings
    name:           cosine        #Name of the LR Scheduler
    warmup_epochs:  5

Data:
  name:               imagenet                  #Dataset Name
  path:               /localdata/ImageNet #Dataset Path
  input_size:         [3, 224, 224]
  augs:               #All augmentation options
    autoaug: original
    random_earse:
      reprob:         0.25
      remode:         pixel
      recount:        1
      resplit:        False
    mixup:
      mixup_alpha:    0.8
      cutmix_alpha:   1.0
      cutmix_minmax:  null
      mixup_prob:     1.0
      mixup_switch_prob:  0.5
      mixup_mode:     batch
      mixup_off_epoch: 0

Plugins:
-
  name:         PrecisionGating
  params:
    skip_layers: [0,]
    wbits:      8
    abits:      8
    pgabits:    4
    threshold:  0.01
    sparse_bp:  False
