#Following the example script of timm library
Experiment:
  exp_id:             test_resnet18            #Experiment Name
  path:               ./checkpoint #Path to save Experiment File, will store in "path/exp_id"
  checkpoint_hist:    10            #Number of checkpoints to keep
  dist:               False         #Start with dist launcher
  seed:               42
  debug:              False         #Enable debug output
  gpu_ids:                        #GPUs to use
    - 0

Model:
  model_name:       resnet18
  pretrained:       True

Trainer:
  name:             ImageClassification
  amp:              True          #Enable Automatic Mixed Precision
  batch_size:       256
  val_batch_size:   256
  epochs:           30
  prefetcher:       True
  eval_metric:      top1
  opt:    #Optimizer Settings
    name:           sgd
    params:
      lr:           0.01        #Initial Learning Rate
      momentum:     0.9
      weight_decay: 2.0e-5
  sched:  #LR Scheduler Settings
    name:           cosine        #Name of the LR Scheduler
    warmup_epochs:  5
    warmup_lr:      0.0001   
    min_lr:         1.0e-6

Data:
  name:               imagenet                  #Dataset Name
  path:               /root/hostPublic/ImageNet #Dataset Path
  input_size:         [3, 224, 224]
  augs:               #All augmentation options
    autoaug: original

Plugins:
-
  name:         PrecisionGating
  params:
    wbits:      8
    abits:      4
    pgabits:    4
    threshold:  0.9
    sparse_bp:  False
